### ISSUE TITLE
URL fragments don't work properly when accessed externally

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vh-hacker-guide#2]
If you are already on the MD page (eg. `https://hackerguide.vandyhacks.org`) and you click a link in the table of contents or whatever, eg. `https://hackerguide.vandyhacks.org/#how-to-prepare` it'll work correctly and immediately skip to that section.

Bug: If you paste that same URL (`https://hackerguide.vandyhacks.org/#how-to-prepare`) in a new tab or new browser window, it WON'T work correctly, and will only get you to the guide, not to the specific section.

**Comment by aadibajpai** [comment]
this happens because on page load it's just linked javascript instead of the actual rendered html so the fragment doesn't trigger 

![image](https://user-images.githubusercontent.com/27063113/94837601-190b9f00-0432-11eb-886e-e387e20a8680.png)

Fix would prob be serving rendered pages

**Comment by aadibajpai** [comment]
fixed in #31
